### ISSUE TITLE
Suggestion / Note

### ISSUE THREAD

**Issue by AEK-BKF** [neelkanthk/laravel-schedulable#9]
Hi,
Thanks for this awesome package.
I have a note regarding Model records fetching, I think it's a wrong idea to affect the standard query which get all rows.
The best / correct way to use the package :
```
$posts = App\Post::get(); // keep the standard method to get all records
$posts = App\Post::expiredScheduled()->get(); // to get expired scheduled records
$posts = App\Post::nextScheduled()->get(); // to get future scheduled records
```
Thanks.

**Comment by neelkanthk** [comment]
Your suggestion has been noted.

Currently you can use the `withoutGlobalScope();` method to skip the default scope applied by this package while fetching the records.

The above approach is mentioned in the readme if you want to have a look about using it.

Thanks.
